spring.application.name=notification-service
# 1. ?????????? ???? ??? ????? ???????
server.port=8085
# 3. Eureka Client: ?????, ??? ????????? Eureka Server
#    ?????: ????? ????????? ?????, ??? ??????? Eureka Server (8761)
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
# 4. ????????? Eureka ???????????????? ? ???????? ?????? (default: true)
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
logging.file.name=logs/notification-service.log
# ?????? ?????
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n
