services:


  # =======================================================
  # БАЗЫ ДАННЫХ (Databases)
  # =======================================================
  user-db:
    image: postgres:15
    container_name: user-db
    environment:
      POSTGRES_DB: user
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432" # Хост: 5434
    volumes:
      - user-db-data:/var/lib/postgresql/data

  inventory-db:
    image: postgres:15
    container_name: inventory-db
    environment:
      POSTGRES_DB: inventory
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432" # Хост: 5433
    volumes:
      - inventory-db-data:/var/lib/postgresql/data

  order-db:
    image: postgres:15
    container_name: order-db
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: user
      POSTGRES_DB: orders
    ports:
      - "5435:5432" # Хост: 5435
    volumes:
      - order-db-data:/var/lib/postgresql/data

  payment-db:
    image: postgres:15
    container_name: payment-db
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: user
      POSTGRES_DB: payments
    ports:
      - "5436:5432" # Хост: 5436
    volumes:
      - payment-db-data:/var/lib/postgresql/data

  # =======================================================
  # 3. БРОКЕР СООБЩЕНИЙ (Kafka)
  # =======================================================
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092" # Открываем внешний порт Kafka
    #      - "9999:9999"        # JMX port для Prometheus

    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # Внешний слушатель для доступа из Spring Boot сервисов (localhost:29092)
      #      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,EXTERNAL://localhost:9092
      #      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      # Слушаем 29092 (внутр.) и 9092 (внешн., который проброшен)
      #      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
#
#    # === JMX ===
#      JMX_PORT: 9999
#      KAFKA_JMX_OPTS: >-
#        -Dcom.sun.management.jmxremote
#        -Dcom.sun.management.jmxremote.local.only=false
#        -Dcom.sun.management.jmxremote.authenticate=false
#        -Dcom.sun.management.jmxremote.ssl=false
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes

  redis-exporter:
    image: oliver006/redis_exporter:latest
    container_name: redis-exporter
    environment:
      - REDIS_ADDR=redis://redis:6379
    ports:
      - "9121:9121"
    depends_on:
      - redis

volumes:
  inventory-db-data:
  user-db-data:
  order-db-data:
  payment-db-data:
