apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      containers:
        - name: inventory-service
          image: autoscale-inventory-service:latest   # Если используешь build из Dockerfile, сначала собери образ
          imagePullPolicy: Never
          ports:
            - containerPort: 8084
          env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://eureka-server:8761/eureka/"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://inventory-postgres:5433/inventory"
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "kafka:29092"
            - name: SPRING_DATA_REDIS_HOST
              value: "redis"
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-service
spec:
  selector:
    app: inventory-service
  ports:
    - port: 8084
      targetPort: 8084
      nodePort: 32084
  type: NodePort
