apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: autoscale-order-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8087
          env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://eureka-server:8761/eureka/"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://order-postgres:5435/orders"
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "kafka:29092"
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    app: order-service
  ports:
    - port: 8087       # порт внутри кластера
      targetPort: 8087 # порт контейнера
      nodePort: 32087
  type: NodePort
