spring.application.name=payment-service
server.port=8082
# Eureka
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
# PostgreSQL Configuration (payment-db)
spring.datasource.url=jdbc:postgresql://localhost:5436/payments
spring.datasource.username=user
spring.datasource.password=pass
spring.datasource.driver-class-name=org.postgresql.Driver
logging.level.com.example.payment_service=DEBUG
# JPA/Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
logging.level.org.springframework.boot.autoconfigure.jdbc=DEBUG
#Metrics
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.prometheus.enabled=true
management.endpoint.metrics.enabled=true
management.metrics.tags.application=payment-service
management.metrics.distribution.percentiles-histogram.http.server.requests=true
management.metrics.distribution.percentiles-histogram.spring.kafka.listener=true
management.metrics.enable.all=true
spring.kafka.consumer.properties.micrometer.enabled=true
spring.kafka.producer.properties.micrometer.enabled=true
spring.kafka.listener.observation-enabled=true
spring.kafka.template.observation-enabled=true
management.metrics.binders.kafka.enabled=true
management.tracing.sampling.probability=1.0
management.observations.key-values.application=payment-service
management.metrics.distribution.percentiles-histogram.all=true
management.metrics.enable.kafka=true


