apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-postgres
  template:
    metadata:
      labels:
        app: inventory-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          env:
            - name: POSTGRES_DB
              value: inventory
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
          ports:
            - containerPort: 5432


---
apiVersion: v1
kind: Service
metadata:
  name: inventory-postgres
spec:
  selector:
    app: inventory-postgres
  ports:
    - port: 5433
      targetPort: 5432
