apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: inventory-service-monitor
  labels:
    release: prometheus   # ← КРИТИЧНО
    app.kubernetes.io/part-of: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: inventory-service
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 15s
