spring.application.name=order-service
# 1. ?????????? ???? ??? ????? ???????
server.port=8087
# 3. Eureka Client: ?????, ??? ????????? Eureka Server
#    ?????: ????? ????????? ?????, ??? ??????? Eureka Server (8761)
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
# 4. ????????? Eureka ???????????????? ? ???????? ?????? (default: true)
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
# PostgreSQL Configuration (order-db)
# ?????????? ???? 5435
spring.datasource.url=jdbc:postgresql://localhost:5435/orders
spring.datasource.username=user
spring.datasource.password=pass
spring.datasource.driver-class-name=org.postgresql.Driver
# JPA/Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
# ??? ?????? ???? ????????????? DEBUG, ????? ?????? ???????????
logging.level.com.example.order_service=DEBUG
# ??? ?????????, ????????, Spring Web, ????????????? WARN, ????? ?????? ?????? ????????
logging.level.org.springframework.web=WARN
# application.properties
spring.kafka.bootstrap-servers=host.docker.internal:9092
#Metrics
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.prometheus.enabled=true
management.endpoint.metrics.enabled=true
management.metrics.tags.application=order-service
management.metrics.distribution.percentiles-histogram.http.server.requests=true
management.metrics.enable.all=true
management.metrics.distribution.percentiles-histogram.spring.kafka.listener=true
spring.kafka.consumer.properties.micrometer.enabled=true
spring.kafka.producer.properties.micrometer.enabled=true
spring.kafka.listener.observation-enabled=true
spring.kafka.template.observation-enabled=true
management.metrics.binders.kafka.enabled=true
management.tracing.sampling.probability=1.0
management.observations.key-values.application=payment-service
# ???????? ??????????? (????? ?????? le="0.001" ? ?.?. ??? ???? ??????)
management.metrics.distribution.percentiles-histogram.all=true
# 4. ????? ??????? Kafka ???? ????? ?????
management.metrics.enable.kafka=true
