spring.application.name=inventory-service
server.port=8084
#eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
#eureka.client.register-with-eureka=true
#eureka.client.fetch-registry=true
# PostgreSQL Configuration (inventory-db)
spring.datasource.url=jdbc:postgresql://inventory-postgres:5433/inventory
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
# JPA/Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.ddl-auto=create-drop

spring.jpa.show-sql=true
logging.level.com.example.inventory_service=DEBUG
logging.level.org.springframework.web=WARN
# application.properties
spring.kafka.bootstrap-servers=host.docker.internal:9092
# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true
#Metrics
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.prometheus.enabled=true
management.endpoint.metrics.enabled=true
management.metrics.tags.application=${spring.application.name}
management.metrics.distribution.percentiles-histogram.http.server.requests=true
management.metrics.enable.all=true
management.metrics.distribution.percentiles-histogram.spring.kafka.listener=true
spring.kafka.consumer.properties.micrometer.enabled=true
spring.kafka.producer.properties.micrometer.enabled=true
spring.kafka.listener.observation-enabled=true
spring.kafka.template.observation-enabled=true
management.metrics.binders.kafka.enabled=true
management.tracing.sampling.probability=1.0
management.observations.key-values.application=inventory-service
management.metrics.distribution.percentiles-histogram.all=true
management.metrics.enable.kafka=true
management.metrics.enable.cache=true
management.metrics.enable.redis=true
spring.data.redis.host=127.0.0.1
#spring.data.redis.host=redis
spring.data.redis.port=6379
spring.data.redis.timeout=2s
spring.cache.type=redis
spring.cache.redis.time-to-live=30s
app.cache.names=inventory, inventory_all

