spring.application.name=eureka-server
# =======================================================
# EUREKA SERVER CONFIGURATION
# =======================================================
# 1. ???? ??????????
server.port=8761
# 3. ????????? ??????? Eureka:
#    ?????: ?????? ?? ?????? ???????? ???????????????? ??? ? ???? (false).
eureka.client.register-with-eureka=false
#    ?????: ?????? ?? ?????? ???????? ????????? ?????? ?? ??????? ??????? (false).
eureka.client.fetch-registry=false
# 4. ????????? ??????????: hostname ??? UI (http://localhost:8761/)
eureka.instance.hostname=localhost
# 5. ?????????? ?????? ?????????? (?????? ??? ??????????!)
# ? ?????????? ??? ?????, ?? ??? ?????? ??????????.
eureka.server.enable-self-preservation=false
