spring.application.name=external-payment-gateway
# =======================================================
# EUREKA CLIENT CONFIGURATION (user-service)
# =======================================================
# 1. ?????????? ???? ??? ????? ???????
server.port=8083
# 3. Eureka Client: ?????, ??? ????????? Eureka Server
#    ?????: ????? ????????? ?????, ??? ??????? Eureka Server (8761)
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
# 4. ????????? Eureka ???????????????? ? ???????? ?????? (default: true)
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
logging.level.com.example.external_payment_gateway=DEBUG
payment.delay.min=200
payment.delay.max=800
payment.fail.probability=0.1


